@url=http://localhost:3000/api

GET {{url}}/autores

###
GET {{url}}/posts

###
GET {{url}}/posts/autor/1

###
POST {{url}}/autores
Content-Type: application/json

{
    "nombre": "Paloma Leonato",
    "email":"paloma@gmail.com",
    "imagen":"url imagen Leonato"
}

###
POST {{url}}/posts
Content-Type: application/json

{
    "descripcion": "dana en Valencia",
    "fecha_creacion": "2024-10-29",
    "categoria": "social",
    "post": "sobre el desastre de la dana en Valencia", 
    "autor_id": "3"
}



